### PR TITLE
update pyi + release publish process (#860)

### PR DESCRIPTION
**Pull request by dinhlongviolin1**
Solve Issue #860

### CODE REVIEW

**Review by FredLL-Avaiga — APPROVED** [review]
So the pyi is not committed anymore, it's only generated and included in the release?

**Comment by dinhlongviolin1** [comment]
> So the pyi is not committed anymore, it's only generated and included in the release?

Yes you are right!

**Comment by dinhlongviolin1** [comment]
> So the pyi is not committed anymore, it's only generated and included in the release?

And private methods and attributes will not be included in the pyi files

**Review by FabienLelaquais — COMMENTED** [review]
👌

**Pull request merged**
