### PR TITLE
feat(stylekit): add a common default padding to CSS components

### PR DESCRIPTION
**Pull request by ghost**
Add a common default padding (through a variable) to CSS components (card, sidebar).

EDIT : It has been stated with @FabienLelaquais that `--component-padding` would become `--element-padding` for clarity.

### CODE REVIEW

**Review by FredLL-Avaiga — APPROVED** [review]

**Comment by ghost** [comment]
`--component-padding` needs renaming as discussed in issue #699 
Waiting for this to be discussed before updating this branch.

**Comment by ghost** [comment]
Waiting for the big class renaming branch to be merged to rebase this one and rename the « components » folder to « elements » to reflect the latest naming decision on former CSS « components » .

**Review by FredLL-Avaiga — APPROVED** [review]

**Review by FabienLelaquais — APPROVED** [review]
That's even how it is documented. Great.

**Review by FabienLelaquais — APPROVED** [review]
That's even how it is documented. Great.

**Comment by ghost** [comment]
Great. @FabienLelaquais @FredLL-Avaiga I let you guys merge this if it’s all good for you.
I don’t have the right to do it myself.

**Pull request merged**
