### PR TITLE
fix import all error (#310)

### PR DESCRIPTION
**Pull request by dinhlongviolin1**
bug Avaiga/taipy-gui#310

### CODE REVIEW

**Review by FredLL-Avaiga — APPROVED** [review]
easy enough

**Review by FredLL-Avaiga — APPROVED** [review]
Should we change the version back to 1.1.... ?

**Review by FredLL-Avaiga — APPROVED** [review]
I will create a separate PR for the 1.1

**Review by FabienLelaquais — APPROVED** [review]
👍

**Pull request merged**
