### PR TITLE
enable e2e test + remove markupsafe

### PR DESCRIPTION
**Pull request by dinhlongviolin1**
Re-enable e2e test

Markupsafe custom installation is not needed anymore since we moved to flask 2

### CODE REVIEW

**Review by FredLL-Avaiga — APPROVED** [review]
Looks good to me
I still don't understand why we needed markupsafe and why we don't need it anymore ?

**Comment by dinhlongviolin1** [comment]
> Looks good to me
> I still don't understand why we needed markupsafe and why we don't need it anymore ?

I don't either. It didn't work on Flask 1 without it due to some dependancies upgrade

**Comment by FredLL-Avaiga** [comment]
> > Looks good to me
> > I still don't understand why we needed markupsafe and why we don't need it anymore ?
> 
> I don't either. It didn't work on Flask 1 without it due to some dependancies upgrade

OK so it's linked to Flask version

**Comment by dinhlongviolin1** [comment]
> > > Looks good to me
> > > I still don't understand why we needed markupsafe and why we don't need it anymore ?
> > 
> > 
> > I don't either. It didn't work on Flask 1 without it due to some dependancies upgrade
> 
> OK so it's linked to Flask version

It is. If you try Flask 1, you still have to install Markupsafe manually. If you use Flask2, you won't need it.

**Review by FabienLelaquais — APPROVED** [review]
👍

**Pull request merged**
