### PR TITLE
fix(pane): add mode class on the pane

### PR DESCRIPTION
**Pull request by ghost**
Address #766 reported by a user.

## Problem
As the Drawer is out of the taipy-dark/light class div, dark mode has no effect on it, especially with the Stylekit that relies on that class name.
pane

## Solution
Add the mode-aware class name on the pane to enable color mode capabilities on that component without moving it into the root div.

### CODE REVIEW

**Review by FredLL-Avaiga — COMMENTED** [review]
Global reformat makes it very uneasy to spot the "real" changes :-(
Another solution would be to change the theme class name at the root level (HTML) ?

**Comment by ghost** [comment]
@FredLL-Avaiga Yes sorry I saw that too and updated that right before you posted your comment :D
Forgot to disable my code formatter.

Yes, changing that at the `<html>` level would be better indeed. But I didn’t see how (and where) to do that in the project structure.

**Review by FredLL-Avaiga — COMMENTED** [review]
I proposed that we drop this PR and we change the current implementation to set the theme class to the body.
What do you think @JaufreyTpy ?

**Comment by ghost** [comment]
@FredLL-Avaiga Fine by me. So I let you change the implementation ?

**Pull request closed without merging**
