### PR TITLE
Rerun tests on Github Action and add MacOSx support

### PR DESCRIPTION
**Pull request by florian-vuillemot**

### CODE REVIEW

**Comment by florian-vuillemot** [comment]
The cost of running their actions is around 5-6euros after a quick calculation.

**Comment by dinhlongviolin1** [comment]
Should we enable the tests now or wait for the public release

**Review by FabienLelaquais — APPROVED** [review]
Looking good!

**Review by dinhlongviolin1 — APPROVED** [review]

**Review by dinhlongviolin1 — CHANGES_REQUESTED** [review]
Optional Package is missing macos test

**Review by dinhlongviolin1 — APPROVED** [review]

**Comment by florian-vuillemot** [comment]
Thanks @dinhlongviolin1

**Pull request merged**
