### PR TITLE
fix logs issue when using with taipy-core (Avaiga/taipy#58)

### PR DESCRIPTION
**Pull request by dinhlongviolin1**
Solve Issue Avaiga/taipy#58

### CODE REVIEW

**Review by jrobinAV — APPROVED** [review]

**Review by FredLL-Avaiga — APPROVED** [review]
if you say so ...
Any impact on gui logs ?

**Comment by jrobinAV** [comment]
Do you plan to merge it into release/1.1 as well ?

**Comment by dinhlongviolin1** [comment]
> if you say so ... Any impact on gui logs ?

Not at all

**Review by FabienLelaquais — APPROVED** [review]
Martin appreciates!

**Pull request merged**
