### PR TITLE
remove doc trigger (#274)

### PR DESCRIPTION
**Pull request by FredLL-Avaiga**

### CODE REVIEW

**Review by florian-vuillemot — APPROVED** [review]

**Review by FabienLelaquais — APPROVED** [review]
A tricky one. You did a perfect job at it.

**Comment by florian-vuillemot** [comment]
Is TRIGGER_OTHER_ACTION still useful?

**Comment by FredLL-Avaiga** [comment]
> A tricky one. You did a perfect job at it.

Tx

**Review by dinhlongviolin1 — APPROVED** [review]

**Comment by FredLL-Avaiga** [comment]
> TRIGGER_OTHER_ACTION

I couldn't find any reference to TRIGGER_OTHER_ACTION in taipy-gui

**Pull request merged**
