### PR TITLE
propagate changes on init file

### PR DESCRIPTION
**Pull request by jrobinAV**
TO BE MERGED in release/2.3.1 to publish a release 2.3.1

If that's OK for you, I let you merge this PR if approved.

### CODE REVIEW

**Review by FredLL-Avaiga — APPROVED** [review]

**Review by FabienLelaquais — APPROVED** [review]
👌

**Comment by jrobinAV** [comment]
Can someone help me understanding why Generate gui.pyi action fails ?

**Review by dinhlongviolin1 — APPROVED** [review]
LTGM

**Comment by dinhlongviolin1** [comment]
> Can someone help me understanding why Generate gui.pyi action fails ?

I believe you didn't merge the changes on taipy config

**Comment by jrobinAV** [comment]
> > Can someone help me understanding why Generate gui.pyi action fails ?
> 
> I believe you didn't merge the changes on taipy config

I did.

**Pull request merged**
