### PR TITLE
Enhance Markdown Parsing For Invalid Control (#628)

### PR DESCRIPTION
**Pull request by dinhlongviolin1**
Solve Issue #628
```python
from src.taipy.gui import Gui

page = """  
# Unknown element

Control: <|Some text|foobar|>
"""

Gui(page).run()
```

### CODE REVIEW

**Review by FabienLelaquais — APPROVED** [review]
Hum that was more impactful than I expected!
Well done!

**Review by FredLL-Avaiga — APPROVED** [review]
Waow !!!
Any impact on the use of library elements without specifying the library ?

**Comment by dinhlongviolin1** [comment]
> Waow !!! Any impact on the use of library elements without specifying the library ?

I am not sure what you mean but I dont think there would be any impact. What I have change mainly is on the preprocessor in case there is no control type found, then I try to resolve whether it is a text or not based on the first property.

**Comment by FredLL-Avaiga** [comment]
> > Waow !!! Any impact on the use of library elements without specifying the library ?
> 
> I am not sure what you mean but I dont think there would be any impact. What I have change mainly is on the preprocessor in case there is no control type found, then I try to resolve whether it is a text or not based on the first property.

Maybe I'm wrong but would the warning show when we're using a (library.)?element  ?

**Comment by dinhlongviolin1** [comment]
> > > Waow !!! Any impact on the use of library elements without specifying the library ?
> > 
> > 
> > I am not sure what you mean but I dont think there would be any impact. What I have change mainly is on the preprocessor in case there is no control type found, then I try to resolve whether it is a text or not based on the first property.
> 
> Maybe I'm wrong but would the warning show when we're using a (library.)?element ?

Can you help me testing that

**Comment by FredLL-Avaiga** [comment]
> > > > Waow !!! Any impact on the use of library elements without specifying the library ?
> > > 
> > > 
> > > I am not sure what you mean but I dont think there would be any impact. What I have change mainly is on the preprocessor in case there is no control type found, then I try to resolve whether it is a text or not based on the first property.
> > 
> > 
> > Maybe I'm wrong but would the warning show when we're using a (library.)?element ?
> 
> Can you help me testing that

Here you are:
```
from taipy.gui import Gui
from taipy.gui.extension import ElementLibrary, Element, ElementProperty, PropertyType

import typing as t

md = """
# Custom test

<|Here is an html title|taipy_extension_example.title|>

<|Here is an html title with no lib|title|>

"""

def render_xhtml(properties: t.Dict[str, t.Any]):
    return f'<div><h1>{properties.get("value", "Default text")}</h1></div>'


class MyLibrary(ElementLibrary):

    elts = {
        "title": Element("value", {
            "value": ElementProperty(PropertyType.string),
        }, "h1", render_xhtml=render_xhtml),
    }

    def get_name(self) -> str:
        return "taipy_extension_example"

    def get_elements(self) -> t.Dict[str, Element]:
        return MyLibrary.elts


Gui.add_library(MyLibrary())
Gui(md).run(debug=True)

```

**Pull request merged**
